### ISSUE TITLE
Changing tags in settings does not change available tags for training in Context Menu when rightclicking a mail

### ISSUE THREAD

**Issue by cadowyn** [minutogit/PrioMailbox#1]
![image](https://github.com/user-attachments/assets/641c4046-dcb7-42c1-a424-3f23b95b3f9c)
![image](https://github.com/user-attachments/assets/55eb7d08-ef1f-4e3e-b486-32be9c5003ed)

**Comment by minutogit** [comment]
Yes. At the moment you have to restart thunderbird when you change your tags. After restart you can choose the changed tags.

**Comment by minutogit** [comment]
Is it still not working, or is it working now?

**Comment by minutogit** [comment]
I found and fixed a bug that likely resolved this issue as well.
