### ISSUE TITLE
Tags are not getting selected from the setting page.

### ISSUE THREAD

**Issue by ozzmanmuhammad** [minutogit/PrioMailbox#2]
When I select the account, tags, and threshold, only the account and threshold get selected and saved. The tags don't save. Any idea what I'm doing wrong here?
![image](https://github.com/user-attachments/assets/1bf2d6f9-5fa5-4832-810f-a97516380550)
![image](https://github.com/user-attachments/assets/e90f29ac-7c21-4ca4-8919-1200238d70bc)

**Comment by minutogit** [comment]
Which version are you using? Maybe try manually installing the latest version 1.0.1 from here. Does it work with that?

If you selected tags and clicked save, but the tags don't appear in the PrioMailbox menu, is that what you mean?

I don't fully understand what isn't working yet. Maybe you could make a quick screen recording to show the issue?

**Comment by minutogit** [comment]
Which version of Thunderbird are you using? Currently, I have no idea why the settings are not being saved.

**Comment by minutogit** [comment]
I found and fixed a bug that likely resolved this issue as well.
